version: '3.4'
services:
  bff:
    container_name: FluentSearch-Spotlight
    restart: always
    environment:
      NODE_ENV: 'development'
      TZ: Asia/Bangkok
      ORIGIN: http(|s):\/\/localhost:5000
      DATABASE_CONNECTION: 'mongodb://fluentsearch-bff-mongos/fluentsearch'
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: FluentSearch@BFF.MongoDB
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: jwt1secret
      JWT_EXPIRES: 300000
      PORT: 5000
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - '5000:5000'
      - '9229:9229'
    volumes:
      - './src:/src'
      - './schema.gql:/schema.gql'
    logging:
      options:
        max-size: 50m
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    volumes:
      - './db:/bitnami'
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: FluentSearch@BFF.MongoDB
